language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.4.1

bundler_args: "--without documentation --path bundle"

before_install:
  - git fetch --depth=1
  - gem install bundler

script:
  - bundle exec danger --verbose
  - bundle exec rake generate_policy_list
  
deploy:
  - provider: s3
    bucket: rs-policysync-tool
    region: us-east-1
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/$WORK_DIR/dist
    acl: public_read
    access_key_id: "$POLICY_SYNC_TOOL_S3_AWS_ACCESS_KEY_ID"
    secret_access_key: "$POLICY_SYNC_TOOL_S3_AWS_SECRET_ACCESS_KEY"
    on:
      branch: master